Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Encoding:
  Enabled: true
  EnforcedStyle: when_needed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250